name: flutter_kinza
description: A new Flutter project
version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  # google_fonts: ^5.1.0 
  supabase_flutter: ^1.10.14
  shimmer: ^3.0.0
  grouped_list: ^5.1.2
  flutter_dotenv: ^5.1.0
  flutter_blurhash: ^0.8.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.7
  rive: ^0.11.16
  telegram: ^0.0.3
  http: ^1.1.0
  timezone: ^0.9.2
  intl: ^0.18.1
  qs: ^0.0.2
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6 

flutter:
  uses-material-design: true
  assets:
    - assets/logo_kinza.svg
    - assets/cat.svg
    - assets/cat.png
    - assets/tetradaka.riv
    - assets/shopping_cart.svg
    - assets/pizza_box.png
    - assets/pizza-deliver.png
    - .env
