name: kinza
description: A new Flutter project
version: 1.0.0

environment:
  sdk: ">=3.7.0 <4.0.0"

flutter:
  uses-material-design: true
  assets:
    - assets/
  shaders:
    - assets/shaders/shimmer.frag

dependencies:
  flutter:
    sdk: flutter

  # UI и анимации
  shimmer: ^3.0.0
  grouped_list: ^5.1.2
  rive: ^0.11.16
  animations: ^2.0.0
  flutter_staggered_animations: ^1.0.0
  flutter_svg: ^2.0.10
  cached_network_image: ^3.3.0
  url_launcher: ^6.3.1
  mask_text_input_formatter: ^2.6.0

  # Данные и сеть
  http: ^1.1.0
  supabase_flutter: ^1.10.14
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  flutter_secure_storage: ^9.2.4

  # Гео-функции
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  timezone: ^0.9.2
  # yandex_mapkit: ^4.1.0
  permission_handler: ^11.3.0

  # Утилиты
  intl: ^0.18.1
  flutter_dotenv: ^5.2.1
  flutter_blurhash: ^0.8.2
  telegram: ^0.0.9
  control: ^0.2.0
  blurhash_ffi: ^1.2.7
  pin_code_fields: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

dependency_overrides:
  win32: ^5.14.0